@startuml
skinparam nodesep 10
hide circle
hide empty members
class "Stressor" [[{A chemical stressor used in exposure experiments.}]] {
    {field} manufacturer : string  
    {field} comments : string  
    {field} uuid(i) : string  
}
class "QuantityValue" [[{A value of an attribute that is quantitative and measurable, expressed as a combination of a unit and a numeric value}]] {
    {field} unit : string  
    {field} numeric_value : string  
}
class "Regimen" [[{The regimen of exposure events.}]] {
    {field} exposure_regimen_type : ExposureRegimenTypeEnum  
    {field} number_of_repeats : integer  
    {field} uuid(i) : string  
}
class "Phenotype" [[{A phenotype observed in the fish as a result of exposure.}]] {
    {field} stage : uriorcurie  
    {field} severity : SeverityEnum  
    {field} phenotype_term_id : uriorcurie  
    {field} uuid(i) : string  
}
"Stressor" *--> "1" "QuantityValue" : "dose"
"Regimen" *--> "0..1" "QuantityValue" : "individual_exposure_duration"
"Regimen" *--> "0..1" "QuantityValue" : "interval_between_exposures"
"Phenotype" *--> "0..1" "QuantityValue" : "prevalence"
"Regimen" *--> "0..1" "QuantityValue" : "time_between_first_and_last_exposure"
class "ChemicalEntity" [[{A chemical compound used as a toxicant in the study.}]] {
    {field} chebi_id : uriorcurie  
    {field} cas_id : string  
    {field} chemical_name : string  
    {field} synonym : string  [0..*]
    {field} uuid(i) : string  
}
class "ExposureEvent" [[{An instance of a toxicological exposure event in the study.}]] {
    {field} vehicle : VehicleEnumeration  [0..*]
    {field} route : ExposureRouteEnum  
    {field} exposure_start_stage : uriorcurie  
    {field} exposure_end_stage : uriorcurie  
    {field} comments : string  
    {field} exposure_type : ExposureTypeEnum  
    {field} additional_exposure_conditions : string  
    {field} uuid(i) : string  
}
abstract "Entity" [[{The base class for all entities in the Zebrafish Toxicology Atlas Schema.}]] {
    {field} uuid : string  
}
"Stressor" *--> "1" "ChemicalEntity" : "chemical"
"ExposureEvent" *--> "0..*" "Stressor" : "stressor_chemical"
"Entity" ^-- "Stressor"
"ExposureEvent" *--> "0..1" "Regimen" : "regimen"
"Entity" ^-- "Regimen"
class "PhenotypeObservation" [[{An observation of phenotypes resulting from exposure experiments.}]] {
    {field} control : boolean  
    {field} uuid(i) : string  
}
"PhenotypeObservation" *--> "0..*" "Phenotype" : "phenotype"
"Entity" ^-- "Phenotype"
class "Image" [[{An image associated with a phenotype observation.}]] {
    {field} magnification : string  
    {field} resolution : string  
    {field} scale_bar : string  
    {field} uuid(i) : string  
}
class "ExposureExperiment" [[{An experiment exposing fish to chemical stressors.}]] {
    {field} standard_rearing_conditions : boolean  
    {field} rearing_condition_comments : string  
    {field} uuid(i) : string  
}
class "Experiment" [[{An experiment within a study.}]] {
    {field} control : boolean  
    {field} uuid(i) : string  
}
"PhenotypeObservation" *--> "0..*" "Image" : "image"
"PhenotypeObservation" *--> "0..1" "ExposureExperiment" : "exposure_experiment"
"Experiment" *--> "0..*" "PhenotypeObservation" : "phenotype_observation"
"Entity" ^-- "PhenotypeObservation"
"Entity" ^-- "Image"
class "Fish" [[{A representation of the zebrafish used in the toxicology study.}]] {
    {field} name : string  
    {field} id : uriorcurie  
    {field} uuid(i) : string  
}
"ExposureExperiment" *--> "0..*" "ExposureEvent" : "exposure_event"
"ExposureExperiment" *--> "0..1" "Fish" : "subject"
"Entity" ^-- "ExposureExperiment"
"Entity" ^-- "Fish"
"Entity" ^-- "ExposureEvent"
class "Study" [[{A toxicology study containing experiments.}]] {
    {field} publication : string  
    {field} contributor : uriorcurie  [0..*]
    {field} lab : uriorcurie  
    {field} uuid(i) : string  
}
"Study" *--> "0..*" "Experiment" : "experiment"
"Entity" ^-- "Experiment"
"Entity" ^-- "Study"
"Entity" ^-- "ChemicalEntity"
@enduml
